### PR TITLE
Fix for #33 : GsonDateTypeAdapter isn't thread safe

### LINKED ISSUE #33: GsonDateTypeAdapter isn't thread safe
In the GsonDateTypeAdapter class, the DateFormat's are private static final.  DateFormat / SimpleDataFormat's are not thread safe (check the JavaDoc of both Java classes - http://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html).

You need to explicitly synchronise on these class variables or you need to create a new instance of the DataFormat in the deserialise method.

### PR DESCRIPTION
**Pull request by meriouma**
Fix #33

### CODE REVIEW

**Comment by christiangoudreau** [comment]
LGTM

**Comment by olafleur** [comment]
LGTM

**Comment by wgauvin** [comment]
You don't need a synchronised list, since you're only ever iterating over it once it's created.  You actually need an immutable list (using the Google Collections you would have ImmutableList.of).  You still need the synchornisation block though.

**Comment by meriouma** [comment]
Good catch

**Comment by wgauvin** [comment]
LGTM

**Pull request merged**
